# Generated by Django 4.2.1 on 2023-06-06 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_predmeti_nositelj'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredmetiAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.predmeti')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
