# Generated by Django 4.2.1 on 2023-06-07 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_predmetiassignment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='predmetiassignment',
            unique_together={('professor', 'predmet')},
        ),
        migrations.CreateModel(
            name='UpisniList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pass', 'Passed'), ('enr', 'Enrolled')], max_length=4)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('predmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.predmeti')),
            ],
        ),
    ]
