# Generated by Django 4.2.1 on 2023-06-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0006_remove_predmeti_nositelj_korisnik_upisnilist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upisnilist',
            name='status',
            field=models.CharField(choices=[('pass', 'Passed'), ('fail', 'Failed'), ('enr', 'Enrolled')], max_length=4),
        ),
    ]
